---
# Example Playbook: cisco.intersight.intersight_storage_policy
# Runs on localhost since policies are only configured once
# Author: Surendra Ramarao (@CRSurendra)
- hosts: localhost
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default('present') }}"
    # Organization name
    org_name: Cloudera-SZR-Org
  tasks:
    - name: Configure Storage Policy
      intersight_storage_policy:
        <<: *api_info
        organization: "{{ org_name }}"
        name: TEST_SP
        description: Storage Policy for lab use
        tags:
          - Key: Site
            Value: RCDN
        default_drive_mode: UnconfiguredGood
        m2_virtual_drive:
          - controller_slot: MSTOR-RAID-1
            enable: true
        unused_disks_state: UnconfiguredGood
        use_jbod_for_vd_creation: true
        secure_jbods: 1-4
        raid0_drive:
          - drive_slots: 7-8
            enable: true
            virtual_drive_policy:
              - access_policy: Default
                drive_cache: Default
                read_policy: Default
                write_policy: Default
                strip_size: 64 


      
        
        


        

        
