---
# Example Playbook: cisco.intersight.intersight_ethernet_netowrk_group_policy
# Runs on localhost since policies are only configured once
# Author: Surendra Ramarao (@CRSurendra)
- hosts: localhost
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default('present') }}"
    # Organization name
    org_name: Cloudera-SZR-Org
  tasks:
    - name: Configure Ethernet Netwrork Group Policy
      intersight_ethernet_network_group_policy:
        <<: *api_info
        organization: "{{ org_name }}"
        name: TEST_ENGP
        description: Ethernet Network Group Policy for lab use
        tags:
          - Key: Site
            Value: RCDN
        vlan_settings:
          - allowed_vlans: 1-4,6
            native_vlan: 1
        
      
        
        


        

        
