---
# Example Playbook: cisco.intersight.intersight_fabric_port_mode
# Runs on localhost since policies are only configured once
# Author: Surendra Ramarao (@CRSurendra)
- hosts: localhost
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default('present') }}"
    # Organization name
    org_name: Cloudera-SZR-Org
  tasks:
    - name: Configure Fabric Port Mode
      intersight_fabric_port_mode:
        <<: *api_info
        tags:
          - Key: Site
            Value: RCDN
        custom_mode: FibreChannel
        port_id_start: 1
        port_id_end: 16
        slot_id: 1
        port_policy: TEST_FPP
    - name: Configure Fabric Port Mode
      intersight_fabric_port_mode:
        <<: *api_info
        tags:
          - Key: Site
            Value: RCDN
        custom_mode: BreakoutEthernet25G
        port_id_start: 49
        port_id_end: 50
        slot_id: 1
        port_policy: TEST_FPP
    - name: Configure Fabric Port Mode
      intersight_fabric_port_mode:
        <<: *api_info
        tags:
          - Key: Site
            Value: RCDN
        custom_mode: BreakoutEthernet10G
        port_id_start: 51
        port_id_end: 52
        slot_id: 1
        port_policy: TEST_FPP
        
        
        
        


        

        
